### ISSUE TITLE
GetDevices doesn't work with SDK Platform Tools 27.0.1

### ISSUE THREAD

**Issue by APTechSupport** [quamotion/madb#113]
Hello there, 

I am using SharpAdbClient 2.1.0, and when using the command GetDevices, I get the following error:

`Invalid device list data '00bc13bcf4bacc62       device product:bullhead model:Nexus_5X device:bullhead transport_id:1'`

This occurs when using Android SDK Platform- Tools 27.0.1 (as of December 2017, the latest version of Platform Tools). 

When I set the environment variable to use an earlier version of adb.exe, this function works. 

The command `adb devices` returns the following:

`List of devices attached
00bc13bcf4bacc62        device`

So it looks like the phone, a Nexus 5x with Android 8.1, is connected and identified. I can also use other apps and commands to communicate with the phone. I've had the same results with a Moto G5 Plus running 7.0, and a Nexus 6 running 7.0 as well. 

Has anyone experiences incompatibilities with Platform Tools 27.0.1 and SharpAdbClient 2.1.0?

**Comment by qmfrederik** [comment]
Thanks for filing an issue. This was fixed in some of the newer prerelease versions, and should be fixed in version 2.2.2 as well. Can you try that version and let me know if you still encounter issues?

**Comment by APTechSupport** [comment]
@qmfrederik Thank you very much, upgrading to 2.2.5 resolved the issue. However, the required package Nerdbank.GitVersioning required us to shuffle around they way we were doing versioning with our project. This is documented in the readme for the package though. 

Again, thank you!

**Comment by qmfrederik** [comment]
I think this is fixed, so closing the issue. Thanks!
