### ISSUE TITLE
OnDeviceConnected serial when fastboot command issues against 1st device

### ISSUE THREAD

**Issue by HygienaJack** [quamotion/madb#119]
I'm writing an WPF application using C# and .NET on a Windows 10 computer. The application is supposed to allow multiple Android devices to be plugged in via USB, then install OS version 4.2.2 and various apps. Initially, the devices were to arrive with OS already installed. My program worked well in an asynchronous fashion.

However, once I had to install the operating system, I needed to boot into fastboot mode (i.e. adb -s [serial-number-here] reboot bootloader). Unfortunately, the OnDeviceConnected() method/event does not fire until the OS is installed and booted back into ADB mode (i.e. fastboot -s [serial-number-here] reboot). The next device in the queue is unfortunately locked by that time, so no further progress can be made, just timeouts from then on.

So, is there a way to allow the Connected and Disconnected events fire asynchronously even if a particular device is booted into fastboot mode?

**Comment by HygienaJack** [comment]
I solved my own problem...

It seems the OnDeviceConnected() and OnDeviceDisconnected() are not completely independent.
I had a blocking process in OnDeviceDisconnected() that took about 3 minutes to complete, so I spun it off on its own thread, which unblocked the next OnDeviceConnected()

The flow went like this:
1. Device in ADB mode is plugged in and OnDeviceConnected() detected it
2. Put connected device in fastboot mode
3. Step #2 caused OnDeviceDisconnected() to fire and installed OS v4.2.2 [blocking problem]

So the solution was to spin a background thread in OnDeviceDisconnected() for installing OS.

**Comment by qmfrederik** [comment]
Yes, the [device monitor is a single loop](https://github.com/quamotion/madb/blob/master/SharpAdbClient/DeviceMonitor.cs) which processes all data coming from adb and will call `OnDeviceConnected` and `OnDeviceDisconnected`.

Currently invoking the events is synchronously - the loop will block until the event is handled and then continue.

We could make this async - see  for example https://stackoverflow.com/questions/1916095/how-do-i-make-an-eventhandler-run-asynchronously. If you really want this, feel free to pop a PR 😄 .
