### ISSUE TITLE
How to run installed package

### ISSUE THREAD

**Issue by JackM36** [quamotion/madb#137]
How do I run one of the installed packages?

I tried using ExecuteRemoteCommand, but I get "adb not found". If I try to cd to the adb folder first, it always says "file or directory not found".

`adb.ExecuteRemoteCommand("cd C:\\adb & adb shell monkey -p com.example.app 1", device, receiver);`

Is there any other way I am missing?

**Comment by qmfrederik** [comment]
The remote command will execute directly on you Android device (consider it equivalent to running `adb shell`). In your case, `adb.ExecuteRemoteCommand("monkey -p com.example.app 1", device, receiver);` will probably do what you want.

**Comment by qmfrederik** [comment]
Closing as I believe this question has been answered.
