### ISSUE TITLE
How to set device Size and DPI

### ISSUE THREAD

**Issue by unominhtuan** [quamotion/madb#143]
Hello, I am looking for how to resize the windows and DPI of NoxPlayer with SharpADBClient.
Can someone help me, I can't find any function to do this
Thanks very much

**Comment by qmfrederik** [comment]
You'd need to find out which adb commands (perhaps via adb shell?) you can send to a NoxPlayer to resize the device. SharpAdbClient can help you only if you can send such commands over adb, and you known which commands to send.

Otherwise, this is out of scope for this project.
