### ISSUE TITLE
Incompatible with ADB 1.0.41 (Version 28.0.3-5475833)

### ISSUE THREAD

**Issue by ajchellew** [quamotion/madb#147]
List Devices is failing on my development machine because Android Studio is running a newer ADB server version.

38:08 E/AdbSocket: Got reply 'FAIL', diag='unknown host service'
Exception thrown: 'SharpAdbClient.Exceptions.AdbException' in SharpAdbClient.dll

**Comment by ajchellew** [comment]
After using wireshark to capturing the new version it appears the `/n` at the end of the request is no longer expected. Changing the code in `AdbClient.cs` as follows works, not sure how you can handle this gracefully when need the new method to get the version.

```
public static byte[] FormAdbRequest(string req)
{
	string resultStr = string.Format("{0}{1}", req.Length.ToString("X4"), req);
	byte[] result = Encoding.GetBytes(resultStr);
	return result;
}
```

**Comment by GustavoFonsecaDeAlmeida** [comment]
#148  I create a pullrequest for this.
