### ISSUE TITLE
unknown host service

### ISSUE THREAD

**Issue by 923789900** [quamotion/madb#149]
“SharpAdbClient.Exceptions.AdbException”类型的未经处理的异常在 SharpAdbClient.dll 中发生 
其他信息: An error occurred while reading a response from ADB: unknown host service

运行不起

**Comment by xiaofeng92** [comment]
Translate:
SharpAdbClient.Exceptions.AdbException: 'An error occurred while reading a response from ADB: unknown host service'.

Unable to run program.

**Comment by 0x317374** [comment]
Same

**Comment by xiaofeng92** [comment]
> 
> 
> Same

This issue has been fixed in PR #155. Or see my repository.

**Comment by innat3** [comment]
I'm getting the same exception, using the latest version (2.2.32)

**Comment by qmfrederik** [comment]
Yeah, #155 should have fixed this. Please reopen if this is not the case.
