### ISSUE TITLE
 StackOverflowException when download direcotry from phone

### ISSUE THREAD

**Issue by Corner514** [quamotion/madb#150]
![image](https://user-images.githubusercontent.com/5234040/60165801-8e052780-9832-11e9-8619-2b21446a90af.png)

Hi,I want to pull some files from the phone, is there anything wrong?  A  StackOverflowException occured because FileListingService and FileSystem is a member of each ohter.

**Comment by mahmoud-hassan-911** [comment]
I have the same issue, did you solve it?
