### ISSUE TITLE
Literal permissions problem in SharpAdbClient.DeviceCommands.PackageManager.SyncPackageToDevice

### ISSUE THREAD

**Issue by dcrespo3d** [quamotion/madb#157]
Hello, I have been trying to install an apk to an Oculus Quest device using PackageManager.InstallPackage and I am getting a PackageInstallationException (with message "An unknown error occured").

Using adb shell I have found my apk under /data/local/tmp with permissions
--w----rw- (204 octal).

I believe there is a problem in [line 255 of PackageManager.cs](https://github.com/quamotion/madb/blob/317946707a246f20b5a0c7ad78c19dc4ac5279ef/SharpAdbClient/DeviceCommands/PackageManager.cs#L255), with the literal "644" for permissions.

I have changed it to 438 (666 octal) and my apk in /data/local/temp now has permissions
-rw-rw-rw- (666 octal).

If I change it to 511 (777 octal) my apk gets -rwxrwxrwx.

Afaik C# doesn't support octal literals (as C does). I have not followed all the calls, but it seems like that literal should be converted from octal to decimal(644 octal is 420 decimal).

**Comment by Studio2B-Berlin** [comment]
Thank you a lot for this fix, I can confirm that I also had trouble pushing the .APK file to a device and changing the literal to 438 fixed my problem!

**Comment by qmfrederik** [comment]
Thanks, this does indeed sound like a bug. Anyone willing to submit a PR?

**Comment by Studio2B-Berlin** [comment]
I can do that, I'll submit a PR later today! 👍

**Comment by qmfrederik** [comment]
Should be fixed via #197 and released on NuGet as version 2.3.23. Feel free to reopen if it's not solved. Thanks!
