### ISSUE TITLE
Connect to Nox Player Using SharpAdbClient

### ISSUE THREAD

**Issue by AmRo045** [quamotion/madb#159]
How can i connect to Nox Player or other emulators using SharpAdbClient?

**Comment by qmfrederik** [comment]
You'd need to find out how to connect your local `adb` to your emulator. Usually you need to call `adb connect [ip]:[port]`, and then you device will show up in `adb devices`.

Does that work for you from the command line? If it does, you can do the same thing using SharpAdbClient.
