### ISSUE TITLE
Remote ADB

### ISSUE THREAD

**Issue by Stephen-Shawn** [quamotion/madb#165]
How to execute the ADB of the specified IP remote host? SSH service is installed (the local host connects the remote host through the network cable, and two ues are connected to the remote host)

**Comment by qmfrederik** [comment]
If adb is exposed as a TCP service, you can just pass the endpoint in the `AdbClient` constructor:

```csharp
var client = new AdbClient(new IPEndPoint(my-remote-ip, 5037), Factories.AdbSocketFactory);
```

If not, you'll need to tunnel the TCP port used by ADB over SSH. That's outside the scope of this project, though.
