### ISSUE TITLE
Device selection question

### ISSUE THREAD

**Issue by SparkYDevtk** [quamotion/madb#166]
I have 5 devices.
I can connect the first
`var device = AdbClient.Instance.GetDevices().First();`
and last
`var device = AdbClient.Instance.GetDevices().Last();`
How can I choose a 2, 3, 4 device?
To send Shell to him
`AdbClient.Instance.ExecuteRemoteCommand("input tap 36 515", device, receiver);
`

**Comment by mostafa901** [comment]
AdbClient.Instance.GetDevices().ElementAt(1)
 AdbClient.Instance.GetDevices().ElementAt(2)
and so on...
You can read more about Enumeration from here 
[Link](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=netframework-4.8)

**Comment by SparkYDevtk** [comment]
> 
> 
> AdbClient.Instance.GetDevices().ElementAt(1)
> AdbClient.Instance.GetDevices().ElementAt(2)
> and so on...
> You can read more about Enumerable from here
> [Link](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=netframework-4.8)

Thanks
