### ISSUE TITLE
Can't find SharpAdbClient.Extensions on Nuget

### ISSUE THREAD

**Issue by clement128** [quamotion/madb#169]
Hi there, I can't find SharpAdbClient.Extensions on Nuget, is it I should download the source code and add to my project?

Thanks

**Comment by qmfrederik** [comment]
Yes, we've completely deprecated SharpAdbClient.Extensions in 149645a7665835317f4e9c82e51a3d3ec64008f9 . You can still use Git to to get access to the older versions, but we have no intention to support them.
