### ISSUE TITLE
Crossplatform compatibility

### ISSUE THREAD

**Issue by tommaier123** [quamotion/madb#208]
Does the library work with .net core on mac or linux?

**Comment by bddckr** [comment]
Yes! It's multi-targeted so it supports multiple target frameworks, one of them is .NET Standard 2.0.

I've successfully used this on Windows, macOS and Linux. You just need to ensure to use the right adb executable for the platform you're running on.

**Comment by tommaier123** [comment]
Awesome, I tried it and it works great. This is the only good crossplatform compatible ADB library I was able to find.
