### ISSUE TITLE
How screenshots

### ISSUE THREAD

**Issue by siterui** [quamotion/madb#34]
How to intercept the screen picture

**Comment by qmfrederik** [comment]
Hi @siterui,

You can take a screenshot by calling `AdbClient.Instance.GetFrameBufferAsync`. It's an async method, but you can use it synchronously by passing `CancellationToken.None` and fecthing its `Result` property. It returns an `Image` which you can use.

Here's an example of code that takes a screenshot of an Android device and saves it as an image.

It'be happy to hear from you how this code works out for you - we've spent quite some time making sure the colors for the screenshots are OK, so let me know if anything is off.

```
// Start the ADB server if required.
// To start the ADB server, uncomment this line and pass the full path to the adb executable.
// AdbServer.Instance.StartServer(@"adb.exe", false);

// Connect to a device. This assumes there is only a single device connected.
var device = AdbClient.Instance.GetDevices().Single();

// Take screenshot of that device.
var screenshot = AdbClient.Instance.GetFrameBufferAsync(device, CancellationToken.None).Result;
screenshot.Save("screenshot.jpg", ImageFormat.Png);
```

Thanks!

Frederik.

**Comment by PhilippCh** [comment]
Do you by chance have any statistics on the performance of the DeviceInfo Screenshot property vs. GetFrameBufferAsync? I'm trying to take and analyze screenshots as fast as possible and currently my main bottleneck is the Screenshot Property (about 2-3 seconds depending on machine load) whereas my adequately complex analysis using OpenCV runs at < .5s.

**Comment by qmfrederik** [comment]
@PhilippCh, `Device.Screenshot` calls `GetFrameBufferAsync` under the hoods so they show similar performance.

The problem with this approach is that `GetFrameBufferAsync` does what its name promises: it takes a full dump of the framebuffer, sends it over the USB wire uncompressed, and converts it to a .NET image. That takes time, and 2-3 seconds on a device with a high resolution is not uncommon.

If high framerate is what you're after, you're probably interested in either:
- A VNC server that runs on Android (there are a couple of them on the Internet), if you're looking for a C# VNC client have a look at [RemoteViewing](https://github.com/qmfrederik/remoteviewing)
- Utilities like [minicap](https://github.com/quamotion/minicap)

You can use SharpAdbClient to get the VNC server/minicap up & running and set up the port forwarding, but implementing clients for VNC/minicap is a bit out of scope for this project.

Hope it helps!

**Comment by siterui** [comment]
Thank you for your answer
