### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by siterui** [quamotion/madb#35]
Are you using this code to delete the file?
`this.Device.ExecuteShellCommand("rm " + remoteFilePath, null);`

No direct call to delete the method?
for example
```
 foreach (var file in service.GetDirectoryListing(directory))
                    {
                        //file.Delete();
                    }
```

**Comment by siterui** [comment]
Is there a demo program that uses SharpAdbClient?
So I can go to study, also won't bother you

**Comment by siterui** [comment]
How to determine the existence of a folder on the phone
thank you

**Comment by qmfrederik** [comment]
Hi @siterui ,

To check for the existence of a file or folder on the phone, use the `SyncService.Stat` method and check the `FileMode` property. If the `FileMode` is `0`, the file or folder does not exist. Else, `FileMode` will tell you whether there is a file or folder at that path.

For example:

```
// Start the ADB server if required.
// To start the ADB server, uncomment this line and pass the full path to the adb executable.
// AdbServer.Instance.StartServer(@"adb.exe", false);

// Connect to a device. This assumes there is only a single device connected.
var device = AdbClient.Instance.GetDevices().Single();

// Figure out whether a file at a given path exists.
string path = "/my/path";

using (ISyncService service = Factories.SyncServiceFactory(device))
{
    bool exists = service.Stat("/my/path").FileMode != 0;

    if(exists)
    {
        Console.WriteLine($"The file {path}  exists");
    }
    else
    {
        Console.WriteLine($"The file {path} does not exist");
    }
}
```

**Comment by qmfrederik** [comment]
Hi @siterui,

You are right, to delete a file, we call `rm -r -f /path/to/file`, there is currently no delete method on a file.

SharpAdbClient provides a very thin layer around `adb`, and just like there is no `adb delete-file` command, there is no (direct) Delete method in SharpAdbClient.

Hope it helps.

**Comment by qmfrederik** [comment]
As for sample code, there currently is some sample code in our [README](https://github.com/quamotion/madb/blob/master/README.md) file, always happy to answer questions here & extend our README file :-)

**Comment by siterui** [comment]
thanks
