### ISSUE TITLE
Alternativ for GetFrameBuffer?

### ISSUE THREAD

**Issue by Viper2k4** [quamotion/madb#39]
Hi,

i have to get a screenshot every 1/2sec. GetFrameBufferAsync work like a charm and took normaly 0.5s for proceed. But is use about 30% CPU-Use if i call it frequently.

Is there maybe an other way to get the Screencontent frequently?

Btw. it also looks ike there is a memory leak in this function because if i run it frequently over a longer time the RAM-Use also grows and grows :)

Greetings

**Comment by qmfrederik** [comment]
Hi,

The performance data you are seeing is expected when using the framebuffer to capture screenshots.

To get high performance screenshots, your options include:
* [minicap](https://github.com/openstf/minicap)
* [screenrecord](http://developer.android.com/tools/help/shell.html#screenrecord)

Hope it helps!

**Comment by qmfrederik** [comment]
Hi @Viper2k4 ,

I'm guessing I've anserwerd your question so I'll go and close this issue for now. If you have further questions - do not hestiate open a new issue.

Thanks!
