### ISSUE TITLE
GetDevices fails if device name contains a white space

### ISSUE THREAD

**Issue by Viper2k4** [quamotion/madb#42]
Hi,

this is bug:

https://github.com/camalot/madb/issues/27

Is also a bug here. It results in an empty list with an "Invalid device list data"-Exception.

Greetings

**Comment by qmfrederik** [comment]
Hi @Viper2k4 ,

Thanks for the feedback! I may need your help to further troubleshoot this -- the bug you reference was reported by me on Codeplex and I've carried over the unit test for that case, it's in [DeviceDataTests](https://github.com/quamotion/madb/blob/master/SharpAdbClient.Tests/DeviceDataTests.cs#L10)

That makes me guess you're having slightly different device data which SharpAdbClient fails to process. Could you let me know which device data you are seeing? Do you have a stack trace?

Thanks!

**Comment by Viper2k4** [comment]
Hi,

i would, but i can not :/

i got this error with a device of on colleague. But i see him next time in one or two weeks. But i try to get the devicename if possible.

Greetings

**Comment by Viper2k4** [comment]
Hi,

no i got access to the devies. Its an Nexus 5X with Android N (prev 3). Here the Error with DeviceData:

`Invalid device list data '0100a9ee51a18f2b       device product:bullhead model:Nexus_5X device:bullhead features:shell_v2,cmd'`

**Comment by qmfrederik** [comment]
Cool, I'll check it & get back to you. Thanks!

**Comment by Viper2k4** [comment]
It looks like the "features:shell_v2,cmd" brakes the regex. If i remove it the regex work well.

**Comment by qmfrederik** [comment]
Thanks, I've just pushed a commit to `master` that should fix this issue, see [this unit test](https://github.com/quamotion/madb/blob/master/SharpAdbClient.Tests/DeviceDataTests.cs#L47).

Let me know if this fixes the issue for you (when you have access to the device :))

**Comment by Viper2k4** [comment]
It should fix the issue. But i cant validate it :(. But it think it should be fine, because the test based 1:1 on "my problem device" :)

I think we can close the issue. If i got an other Error i will report it ^^

**Comment by Viper2k4** [comment]
So i got my hands on the device and i can 100% proof that the fix work :)
