### ISSUE TITLE
Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'

### ISSUE THREAD

**Issue by ShuangpengPang** [quamotion/madb#46]
Hi,
When I got devices with the following code:

try
{
	var devices = AdbClient.Instance.GetDevices();
	foreach (var device in devices)
	{
		Console.WriteLine(device.Name);
	}
}
catch (Exception e)
{
	Console.WriteLine(e.StackTrace);
}

It throwing an exception likes this:
Exception thrown: 'System.TypeInitializationException' in SharpAdbClient.dll
   at SharpAdbClient.AdbServer.get_Instance() location C:\projects\madb\SharpAdbClient\AdbServer.cs:line 113
   at Dot42.AdbLib.DeviceMonitor.Run() location E:\WorkRelated\Projects\UTester-windows\UTestor\AdbLib\DeviceMonitor.cs:line 161
Step into: Stepping over property 'SharpAdbClient.AdbServer.get_Instance'.  To step into properties, go to Tools->Options->Debugging and uncheck 'Step over properties and operators (Managed only)'.
Exception thrown: 'System.TypeInitializationException' in SharpAdbClient.dll
Step into: Stepping over property 'System.Console.get_Out'.  To step into properties, go to Tools->Options->Debugging and uncheck 'Step over properties and operators (Managed only)'.
   at SharpAdbClient.AdbServer.get_Instance() location C:\projects\madb\SharpAdbClient\AdbServer.cs:line 113
   at Dot42.AdbLib.DeviceMonitor.Run() location E:\WorkRelated\Projects\UTester-windows\UTestor\AdbLib\DeviceMonitor.cs:line 161

How to solve this problem? Thanks!

**Comment by qmfrederik** [comment]
Hi @ShuangpengPang,

Thanks for reporting this! We'll be removing the dependency on Mono.Posix soon so this issue should go away.

If this is currently blocking you, can you try to add a reference to the Mono.Posix NuGet package?

**Comment by ShuangpengPang** [comment]
@qmfrederik : Thank you for your reply! This issue was solved When I adding "Mono.Posix.dll" to the folder: /bin/Debug. Thanks!

**Comment by Viper2k4** [comment]
Looks like this is addes some hours ago. Could we Update the nuget-packed? I would love to reduce the dependency :)

**Comment by qmfrederik** [comment]
I've released version [2.1.0-beta291](https://www.nuget.org/packages/sharpadbclient/2.1.0-beta291) to NuGet. You'll need to enable prerelease versions on NuGet to see it.

Can you give this version of the package a try and let me know if it works for you?

**Comment by Viper2k4** [comment]
It does not install on my .net 4.5.2 projekt:

"Das Paket "Microsoft.NETCore.Targets 1.0.1-rc2-24027" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf ".NETFramework,Version=v4.5.2" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten."
(sry german error message :/)

But it simply said that "Microsoft.NETCore.Targets 1.0.1-rc2-24027" does not contains any assembly references for ".NETFramework,Version=v4.5.2" 

And the nuget would like to install ALL this:

![needed](https://cloud.githubusercontent.com/assets/15054322/16058271/f6e7c5e6-327d-11e6-935b-57e364555a9d.PNG)
(Is all this needed?)

**Comment by qmfrederik** [comment]
Sorry for that! I've pushed a new version to NuGet (`2.1.0-beta292`) which should fix that. Let me know if this works for you.

**Comment by Viper2k4** [comment]
This installed just fine :)

**Comment by qmfrederik** [comment]
@ShuangpengPang , haven't heard back from you but based on feedback from others, this should be working.

Feel free to reopen if you are still experiencing issues with this!
