### ISSUE TITLE
Memory leak in RefreshAsync  while using a CancellationToken?

### ISSUE THREAD

**Issue by Viper2k4** [quamotion/madb#50]
Hi,

it is me or is RefreshAsync creates a memory leak if using with a CancellationToken? If i use it like the sample (CancellationToken.None) it workes like a charm. But if i pass through the CancellationToken into the function the memory use increase (faster on fast responed devices like Emulators(Nox,Bluestacks) and slowly on normal devices). My Test-Function:

```
static void Main(string[] args)
{
    var ct = new CancellationTokenSource();
    TestCancellationToken(ct.Token);
    Console.ReadKey();
}

private static async void TestCancellationToken(CancellationToken ct)
{
    var device = AdbClient.Instance.GetDevices().First();

    var framebuffer = AdbClient.Instance.CreateRefreshableFramebuffer(device);

    while (!ct.IsCancellationRequested)
        await framebuffer.RefreshAsync(ct).ConfigureAwait(false);
}
```

**Comment by qmfrederik** [comment]
Hi,

I had a quick look at the code and couldn't immediately spot a different code path based on the cancellation token being set (actually, the code never really checks for `CancellationToken.None`).

Did you run both tests in Debug or Release mode? Do you have an indication of how much memory you see being leaked?

**Comment by Viper2k4** [comment]
The increase is very slow but look here:

![unbenannt](https://cloud.githubusercontent.com/assets/15054322/16173299/32c579a6-359d-11e6-9889-89e80bb6f62d.PNG)
(TestCancellationToken(ct.Token))

![unbenannt1_debug](https://cloud.githubusercontent.com/assets/15054322/16173301/3afe3234-359d-11e6-8ff8-2c84f671f78e.PNG)
(TestCancellationToken(CancellationToken.None))

The Screenshots are both in DEBUG. But i run in Release an got the same Values. I take two memory snapshats (while the memory use increases) and it looks like this:

![sdf](https://cloud.githubusercontent.com/assets/15054322/16173312/ce44493e-359d-11e6-97ec-65969e7393d6.PNG)

And it looks like the "SocketExtensions"-Class could be the Problem.

**Comment by qmfrederik** [comment]
Great catch, thanks! That does indeed seem to be the problem - `CancellationToken.Register` returns a `CancellationTokenRegistration` which should be disposed of, something we currently don't do.

I'm trying to find a Roslyn analyzer that catches these kind of exceptions, so I can add them to the project and make sure these kinds of issues don't come up again. It seems that `Microsoft.Maintainability.Analyzers` (which includes [DoNotIgnoreMethodResults](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.Maintainability.Analyzers/Core/DoNotIgnoreMethodResults.cs)) together with `SonarLint` (which includes ["IDisposables" should be disposed
](http://www.sonarlint.org/visualstudio/rules/index.html#sonarLintVersion=2.3.0&ruleId=S2930)) should do it, but I'm having some issues setting it up.

I'll keep you posted!

**Comment by qmfrederik** [comment]
Hi,

I've prepared a PR - #52, and an updated NuGet release, `2.1.0-beta301`, that should address this issue.

Can you have a look and let me know if this resolves the issue?

Thanks!

**Comment by Viper2k4** [comment]
The Memory-Use is now as expected. Perfect :)

But is SonarLint needed for the enduser?

![unbenannt](https://cloud.githubusercontent.com/assets/15054322/16180079/695bc906-367a-11e6-862c-51dfdb4d0cca.PNG)

**Comment by qmfrederik** [comment]
Ah, my bad!

I've pushed `2.1.0-beta303` to NuGet which should fix this.

Thanks!

**Comment by Viper2k4** [comment]
Perfekt :)

Thx for this
