### ISSUE TITLE
How can i use the class FileSystem

### ISSUE THREAD

**Issue by gfrancischini** [quamotion/madb#53]
Hello,

The class FileSystem inside the module extensions does not seem to be available on nuget package.

I would like to use it to delete some files on device.

How can I achieve that?

Thanks

**Comment by qmfrederik** [comment]
Hi,

We haven't published the `FileSystem` class yet as we're not very happy with its current behavior.

If you want to delete a file, for now, I'd recommend you just execute a shell command and pass `rm [path]` to the command, see the [run shell commands](https://github.com/quamotion/madb#run-shell-commands) section in the readme for more info on how to do that.

Let me know if that helps,

**Comment by qmfrederik** [comment]
We're not planning to support `FileSystem`-like behavior as part of SharpAdbClient.
