### ISSUE TITLE
How do I use your example DownloadFile() function? The AdbSocket requires some EndPoint value to initialise

### ISSUE THREAD

**Issue by atoaster** [quamotion/madb#54]
When I copy and paste your code, it seems that AdbSocket requires an argument

**Comment by qmfrederik** [comment]
Can you try to pass `AdbServer.Instance.EndPoint` as the argument?

**Comment by atoaster** [comment]
Thanks for the fast response!

I unfortunately still get an error saying I can't convert from `System.Net.Endpoint` to `SharpAdbCLient.IAdbSocket`
`using (SyncService service = new SyncService(AdbServer.Instance.EndPoint, device))` 

Am I entering the code in wrong?

sorry for the naivety!

**Comment by atoaster** [comment]
Hey, got it working!

Now I just need to figure out how to pull folders!

Thanks qmfrederik!
