### ISSUE TITLE
How to stop ExecuteRemoteCommand

### ISSUE THREAD

**Issue by lufivuahaitac** [quamotion/madb#57]
I'm writing uiautomator test program. I'm can start shell with ExecuteRemoteCommand but i don't know how to stop it. (In cmd is Ctrl+C). Can't Anyone Help Me? Thanks.

**Comment by qmfrederik** [comment]
@lufivuahaitac , you don't provide a lot of information, but if you want to stop the code on the PC side, you can use the `ExecuteRemoteCommandAsync` method. You can pass a `CancellationToken` which you can use to cancel the remote execution.

```
var device = AdbClient.Instance.GetDevices().Single();
var cancellationTokenSource = new CancellationTokenSource();
var receiver = new ConsoleOutputReceiver();

var task = AdbClient.Instance.ExecuteRemoteCommandAsync("test", device, receiver, cancellationTokenSource.Token, int.MaxValue);

// Your code is now executing. You can now:
// - Read the output using the receiver
// - Cancel the task like shown below:
cancellationTokenSource.Cancel();
```

This does not necessarily stop any tasks you launched on the device. If you can give more information about what you're doing, it may be easier for us to help you.

Thanks!

**Comment by lufivuahaitac** [comment]
Thanks, this is exactly what I want. Thanks again

**Comment by qmfrederik** [comment]
@lufivuahaitac You're welcome!
