### ISSUE TITLE
readme in the root is wrong

### ISSUE THREAD

**Issue by bestfc** [quamotion/madb#63]
Especially the ability to push files.
using (SyncService service = new SyncService(new AdbSocket(), device)) //new AdbSocket() is wrong
    using (Stream stream = File.OpenRead(@"C:\MyFile.txt"))
    {
        service.Push(stream, "/data/MyFile.txt", null, CancellationToken.None);     //params is wrong
    }

**Comment by qmfrederik** [comment]
@bestfc It took a while but I updated the readme file :). Hope it helps!
