### ISSUE TITLE
Problem with "v2.1.0-beta334"

### ISSUE THREAD

**Issue by Viper2k4** [quamotion/madb#65]
I got the following error on update from nuget:

> Failed to add reference. The package 'SharpAdbClient' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance

Btw. as  u can see here:

https://www.nuget.org/packages/sharpadbclient/2.1.0-beta334

It would likt to install System.Buffers (>= 4.3.0) on NETFramework 4.5 which is also included since 1.1 ;)

**Comment by qmfrederik** [comment]
Thanks for letting me know! Should be fixed with the latest version on NuGet (337), let me know if it helps!

**Comment by Viper2k4** [comment]
Same Error :'(

> Failed to add reference. The package 'SharpAdbClient' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by qmfrederik** [comment]
I think I found it :). Can you try beta338?

**Comment by Viper2k4** [comment]
Installes just fine 👍
