### ISSUE TITLE
SharpAdbClient push

### ISSUE THREAD

**Issue by tkggusraqk** [quamotion/madb#68]
public void Push(Stream stream, string remotePath, int permissions, DateTime timestamp, IProgress<int> progress, CancellationToken cancellationToken);

permissions 该怎么赋值

**Comment by qmfrederik** [comment]
@tkggusraqk Can you please report issues in English? Thanks!

**Comment by tkggusraqk** [comment]
@qmfrederik sorry,My English is not very good。
public void Push(Stream stream, string remotePath, int permissions, DateTime timestamp, IProgress progress, CancellationToken cancellationToken); 
this problem，permissions How assignment？ 
other，the method Can not be correctly implemented, the exception

**Comment by qmfrederik** [comment]
@tkggusraqk You need to specify the permissions you want to assign to the file on the Android device, in Linux octal notation.

You can find more information here: https://en.wikipedia.org/wiki/File_system_permissions#Numeric_notation

In short:
- 444 if you wan to grant everyone read access
- 666 if you want to grant everyone write access

and so forth

**Comment by qmfrederik** [comment]
@tkggusraqk I'm going to go ahead & close this issue as I assume my last answer helped you close the issue. Feel free to reopen if that's not the case. Thanks!
