### ISSUE TITLE
Compile error in extensions

### ISSUE THREAD

**Issue by Anth0ny229** [quamotion/madb#69]
There is a compile error in method RunLogService in file Device.cs

        public IEnumerable<LogEntry> RunLogService(params LogId[] logNames)
        {
            return AdbClient.Instance.RunLogService(this.DeviceData, logNames);
        }
Error	CS1061	'IAdbClient' does not contain a definition for 'RunLogService' and no extension method 'RunLogService' accepting a first argument of type 'IAdbClient' could be found (are you missing a using directive or an assembly reference?)

It seems that there is only RunLogServiceAsync.

I just commented it out since I don't need it within my project but it would be nice if I could use the project as it is on GitHub.

Also, Would it be possible if the extensions were included automatically in the SharpAdbClient nuget package that way you don't have to add the project to your solution.

Great work so far thank you for the amazing wrapper!!!

**Comment by qmfrederik** [comment]
@Anth0ny229 Yes, we don't really maintain the extensions code at this moment, that's why it's not in the NuGet package either.

That said, I'd be happy to take a PR that fixes this - I guess the trick here would be to make RunLogService in `Device.cs` async, too.
