### ISSUE TITLE
Exception with latest version of Java while using ExecuteRemoteCommand()

### ISSUE THREAD

**Issue by saurabhben10** [quamotion/madb#70]
I recently updated to the latest version of Java .i.e. Version 8 Update 121

When I execute any command on my sqlite3 database in my android app, this exception comes along with the expected result:
**Code**
`AdbClient.Instance.ExecuteRemoteCommand("sqlite3 /data/data/com.TestApp/databases/msgstore.db \"select _name, _id from joiners order by _id desc limit 1\"", device, receiver);`

**Exception**
Error: Unknown option: -
java.lang.NullPointerException
	at com.android.commands.am.Am.runStart(Am.java:807)
	at com.android.commands.am.Am.onRun(Am.java:285)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:91)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:258)
	at dalvik.system.NativeStart.main(Native Method)
Saurabh Sharma|29

The last line contains the expected result.

**Comment by qmfrederik** [comment]
@saurabhben10 This looks like an issue on the device. Do you get the same error when you open a shell connection to the device using `adb shell` from the command line?

If so, it's an issue on your device and the library is merely reporting that issue back - that's what it is expected to do.

**Comment by saurabhben10** [comment]
@qmfrederik Yes, I faced the same issue while using `adb shell`. FYI, this issue was not there until I hadn't updated my Java Version to the version I mentioned above. 
Soon after updating, I started getting this issue.

**Comment by qmfrederik** [comment]
@saurabhben10 If you have the same issue when using adb shell, I'm afraid it's a low level issue on your device. All SharpAdbClient is doing is connecting to your device, executing the command and sending you back the results - so it's doing what it can.

Closing this for now as "not an issue in SharpAdbClient".
