### ISSUE TITLE
InstallPackage does not work

### ISSUE THREAD

**Issue by xplicit** [quamotion/madb#75]
`InstallPackage` tries to copy apk file to temporary directory on device and then install it. It gets this constant, but this path does not exist (at least at my emulator) and `InstallPackage` fails.

```csharp
public const string TempInstallationDirectory = "/storage/sdcard0/tmp/";
```

For my case I changed it to `/local/data/tmp` and install started to work.

**Comment by qmfrederik** [comment]
@xplicit Thanks for reporting this! `/storage/sdcard0/tmp` definitively isn't the correct location to push files to.

Out of curiosity, could you check what the `EXTERNAL_STORAGE` environment variable points to on your emulator? Is that path writable?

**Comment by dgadelha** [comment]
AFAIK, the default path to push APKs for installations is `/data/local/tmp/`

**Comment by xplicit** [comment]
`echo $EXTERNAL_STORAGE` shows `/storage/sdcard`

I think this option should be configurable at least, because currently it's a `const` and to change it I had to copy the sources from `PackageManager` class, rename it and insert into my project.
