### ISSUE TITLE
Package Manager broken with Android O beta

### ISSUE THREAD

**Issue by ac87** [quamotion/madb#79]
With O it appears there is a base64 checksum in the directory of third party packages. 

`package:/data/app/com.google.android.apps.plus-qQaDuXCpNqJuQSbIS6OxGA==/base.apk=com.google.android.apps.plus`

The additional `=` breaks the check in `PackageManagerReceiver` on `line.Split(':', '=')`

**Comment by qmfrederik** [comment]
@ac87 Thanks - version 2.2.0-beta386 on NuGet should fix this.

Let me know if it works for you!

**Comment by ac87** [comment]
@qmfrederik Looks good to me.

The line `string[] parts = line.Split(':', '=');` is redundant now though.
