### ISSUE TITLE
Any C# samples to get me started

### ISSUE THREAD

**Issue by chapman57** [quamotion/madb#90]
I am very interested in using this class but am having a heck of a time  in C#.

I have added SharpAdbClient to my project using NuGet package manager.

For instance - I would like to setup  Device Monitoring and have implemented the following in my Form Load event:
            AdbServer.Instance.StartServer(@"C:\adb.exe", true);
            DeviceMonitor adbMonitor = new DeviceMonitor(new AdbSocket(AdbServer.Instance.EndPoint));
            adbMonitor.DeviceConnected += this.OnDeviceConnected;
            adbMonitor.DeviceDisconnected += this.OnDeviceDisconnected;
            adbMonitor.Start();

I get an error when initializing the new DeviceMonitor telling me that AdbServer does not contain a definition for EndPoint - yet this code is your example.

Any assistance or a small sample C# app to get me started would be greatly appreciated.

**Comment by qmfrederik** [comment]
@chapman57 I updated the code samples, hope you find them useful now!

**Comment by chapman57** [comment]
Thank you **VERY** much for the updates and the fast reply. I now have the device monitor working and generating connect/disconnect events.

I also learned I need Visual Studio started as administrator to avoid an exception when I call startServer.

Kind Regards,
Don

**Comment by qmfrederik** [comment]
@chapman57 I'm closing this issue as it seems the examples helped you - thanks for your feedback!

**Comment by chapman57** [comment]
I thought I sent a reply. Yes, I am all set and thank you Very Much!

Don

**Comment by Bluscream** [comment]
Could you please add example how to subscribe to broadcasts like http://madb.bit13.com/#managed-adb-installreceiver and http://madb.bit13.com/#managed-adb-installreceiver
