### ISSUE TITLE
Device State always showing Offline

### ISSUE THREAD

**Issue by chapman57** [quamotion/madb#95]
Hi,

I have SharpADB working and I get the Device Connected event when I cradle mu device. However the eventargs aare only populated with the Device Serial and the STATE shows Offline.

Can you think of any reason the device would be OFFLINE, even though I get the events and can read the serial number in the eventargs?

Thanks Much!

**Comment by qmfrederik** [comment]
What does `adb devices` show?

**Comment by qmfrederik** [comment]
@chapman57 There's not much I can do here if I don't have the output of `adb devices`, so I'm going to close this for now. Feel free to re-open once you have more info to share.
